data:
    train:
        type: RaceDataset
        dataset_cfg:
            split: train
        add_space: True
    val:
        type: RaceDataset
        dataset_cfg:
            split: validation
        add_space: True
    test:
        type: RaceDataset
        dataset_cfg:
            split: test
        add_space: True
