_base_: ["./ss_kl_arc_c_llama2_7b.yaml"]

data:
    train:
        noisy_level: 0.3

edl_loss_cfg:
    reg_weight_cfg:
        # turn down reg_weight a bit, otherwise the model will not converge
        final_reg_weight: 0.1
