_base_: ['../obqa_mistral_7b/map_obqa_mistral_7b.yaml']

model:
    peft_path: ""

data:
    test:
        type: CSQADataset
        dataset_cfg:
            # CSQA test set has no labels, so we use the validation set for evaluation.
            split: validation
        add_space: True
        subset_size: null

process_preds:
    npz_file: 'csqa.npz'
