_base_: ['../obqa_llama2_7b/map_obqa_llama2_7b.yaml']

model:
    peft_path: ""

data:
    test:
        type: SciQDataset
        dataset_cfg:
            split: test
        add_space: True

process_preds:
    npz_file: 'sciq.npz'
