_base_: ['../obqa_llama2_7b/map_obqa_llama2_7b.yaml']

model:
    peft_path: ""

data:
    test:
        type: ARCDataset
        dataset_cfg:
            split: test
        name_suffix: "E"
        add_space: True
        subset_size: null

process_preds:
    npz_file: 'arc_e.npz'
